service: serverless-starter

provider:
  name: aws
  runtime: nodejs4.3

functions:
  mechajira-loop:
    handler: mechajira-loop-lambda.handler
    events:
      - http:
          path: mechajira-loop-lambda
          method: get
      - http:
          path: mechajira-loop-lambda
          method: post
  multiCreate:
    handler: multiCreate.handler
    events:
      - http:
          path: multi/create
          method: get
  multiShow:
    handler: multiShow.handler
    events:
      - http:
          path: multi/show/{id}
          method: get
